version: '3.8'
services:
  app:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile
    container_name: portfoliomailer-backend
    ports:
      - "8080:8080"
    env_file:
      - ./conf.env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080